language: bash
services: docker

env:
  - TAG=latest VARIANT=debian
  - TAG=alpine VARIANT=alpine

script:
  - docker build -t "xcezx/gaurun:${TAG}" -f ${VARIANT}/Dockerfile ${VARIANT}
  - docker run -it --rm "xcezx/gaurun:${TAG}" gaurun -v

after_script:
  - docker images
